version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Running Angular unit tests..."
      - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI

  post_build:
    commands:
      - echo "Unit tests completed successfully."